### ISSUE TITLE
grunt-contrib-concat not working with grunt watch.

### ISSUE THREAD

**Issue by ismael-rivera** [gruntjs/grunt-contrib-concat#147]
I don't know if g-c-c is supposed to work with grunt-watch but I coould've sworn I have used it this way before. In any event, I've been using grunt for years but I haven't been using it in last six months. I couldn't find anything on it. Do I need to check the changelogs or is this still an option? As far as I can tell my Gruntfile.js seems legit and the code for the watch task seems OK.

-----------------
watch: {
		compass: {
    		files: ['assets/sass/**/*.{scss,sass}'],
    		tasks: ['compass', 'concat']
  		},
  		livereload: {
    		files: ['*.html', '*.php', 'assets/**/*.{png,jpg,jpeg,gif,webp,svg,js,css}'],
    		options: {
      			livereload: true
    		},
  		},
	 	
	 },
------------------

It should be working. I can't seem to find anything I might have done wrong here. Is concat still a watchable task?

**Comment by shama** [comment]
All tasks are watchable because they operate independently of each other. `grunt-contrib-watch` just watches files then runs the tasks using Grunt when a file specified changes.

I'm not sure what specific issue you're running into above as the section of config isn't formatted in a readable way. But concat and watch works for me. So I'm guessing it's not watching a file you intended or there is some condition unique to your setup causing the issue.
