### ISSUE TITLE
Fail is a src file does not exist

### ISSUE THREAD

**Issue by ibc** [gruntjs/grunt-contrib-concat#15]
If `src` is set with a non existing/readable file (or with an array containing at least one non existing/readable file) then the task does not fail nor warns about it.

I'd strongly prefer it to fail, or at least it would be useful a new option "checkSrcFile" (false by default). If set to true then the concat task would fail if any of the files in `src` does not exist.

**Comment by plaa** [comment]
I was very surprised that concatenation of missing files during build time does not fail by default.  I'm astounded that you cannot even configure it to fail.

We had our build concatenate CSS files, and one of the files went missing.  Instead of failing the build as it should, we just got a build with some of our styles missing.  This is simply unacceptable for a build.  (A warning is in no way sufficient - builds are generated automatically and produce easily 100+ lines of output, no one will notice a warning in the output.)

Does anyone have a workaround for this issue?

**Comment by qqilihq** [comment]
I would also heavily appreciate a fail-on-null functionality.

**Comment by worc** [comment]
this continues to be a problem 2 years on (v0.5.1) and should not have been closed. concat does not throw an error or even warn if a file is missing. in essence concat *fails to fail*. that's completely unacceptable behavior.

integrating concat with build automation or other integration tools is now entirely suspect. no build can truly be green if concat doesn't recognize missing files as a bad state.

**Comment by Taytay** [comment]
I am currently using the following workaround. I added a filter task to the concat task, as follows:

```
            filter: function (filepath) {
                if (!grunt.file.exists(filepath)) {
                    grunt.fail.warn('Could not find: ' + filepath);
                } else {
                    return true;
                }
            },
            nonull: true 
```

Now it fails if there is a non-existent file.
